const translations = {
  'en-US': {
    'heading': 'A tiny i18n library for small React apps',
    'description': 'Polang offers a {{provider}}, a {{hook}} and a {{selector}}, three tiny pieces that internationalize your React app with almost no effort.',
    'description_provider': 'provider',
    'description_hook': 'translation hook',
    'description_selector': 'language selector',
  },
  'pt-BR': {
    'heading': 'Mini biblioteca i18n para pequenas aplicações React',
    'description': 'Polang oferece um {{provider}}, um {{hook}} e um {{selector}} — três componentes mínimos que te ajudam a internacionalizar sua aplicação React quase sem nenhum esforço.',
    'description_provider': 'provider',
    'description_hook': 'hook de tradução',
    'description_selector': 'seletor de idioma',
  },
  'es-ES': {
    'heading': 'Una pequeña biblioteca i18n para aplicaciones React pequeñas',
    'description': 'Polang ofrece un {{provider}}, un {{hook}} y un {{selector}}: tres piezas mínimas que internacionalizan tu aplicación React casi sin esfuerzo.',
    'description_provider': 'proveedor',
    'description_hook': 'hook de traducción',
    'description_selector': 'selector de idioma',
  },
  'fr-FR': {
    'heading': 'Une petite bibliothèque i18n pour les petites applications React',
    'description': 'Polang propose un {{provider}}, un {{hook}} et un {{selector}} — trois briques minimales qui internationalisent votre application React presque sans effort.',
    'description_provider': 'fournisseur',
    'description_hook': 'hook de traduction',
    'description_selector': 'sélecteur de langue',
  },
  'de-DE': {
    'heading': 'Eine kleine i18n-Bibliothek für kleine React-Apps',
    'description': 'Polang bietet einen {{provider}}, einen {{hook}} und einen {{selector}} — drei kleine Bausteine, die Ihre React-App mit fast keinem Aufwand internationalisieren.',
    'description_provider': 'Provider',
    'description_hook': 'Übersetzungs-Hook',
    'description_selector': 'Sprachauswahl',
  },
  'nl-NL': {
    'heading': 'Een kleine i18n-bibliotheek voor kleine React-apps',
    'description': 'Polang biedt een {{provider}}, een {{hook}} en een {{selector}} — drie kleine onderdelen die je React-app met bijna geen moeite meertalig maken.',
    'description_provider': 'provider',
    'description_hook': 'vertaal-hook',
    'description_selector': 'taalselector',
  },
  'it-IT': {
    'heading': 'Una piccola libreria i18n per piccole app React',
    'description': 'Polang offre un {{provider}}, un {{hook}} e un {{selector}} — tre pezzi minimi che internazionalizzano la tua app React quasi senza sforzo.',
    'description_provider': 'provider',
    'description_hook': 'hook di traduzione',
    'description_selector': 'selettore di lingua',
  },
  'da-DK': {
    'heading': 'Et lille i18n-bibliotek til små React-apps',
    'description': 'Polang tilbyder en {{provider}}, en {{hook}} og en {{selector}} — tre små byggeklodser, der internationaliserer din React-app næsten uden indsats.',
    'description_provider': 'provider',
    'description_hook': 'oversættelses-hook',
    'description_selector': 'sprogvælger',
  },
  'sv-SE': {
    'heading': 'Ett litet i18n-bibliotek för små React-appar',
    'description': 'Polang erbjuder en {{provider}}, en {{hook}} och en {{selector}} — tre små delar som internationaliserar din React-app nästan utan ansträngning.',
    'description_provider': 'provider',
    'description_hook': 'översättnings-hook',
    'description_selector': 'språkväljare',
  },
  'nb-NO': {
    'heading': 'Et lite i18n-bibliotek for små React-apper',
    'description': 'Polang tilbyr en {{provider}}, en {{hook}} og en {{selector}} — tre små brikker som internasjonaliserer React-appen din med nesten ingen innsats.',
    'description_provider': 'provider',
    'description_hook': 'oversettelses-hook',
    'description_selector': 'språkvelger',
  },
  'ru-RU': {
    'heading': 'Небольшая i18n-библиотека для небольших React-приложений',
    'description': 'Polang предлагает {{provider}}, {{hook}} и {{selector}} — три крошечных блока, которые почти без усилий добавляют локализацию вашему React-приложению.',
    'description_provider': 'провайдер',
    'description_hook': 'хук перевода',
    'description_selector': 'выбор языка',
  },
  'hi-IN': {
    'heading': 'छोटी React ऐप्स के लिए एक छोटी i18n लाइब्रेरी',
    'description': 'Polang एक {{provider}}, एक {{hook}} और एक {{selector}} देता है — तीन छोटे हिस्से जो आपकी React ऐप को लगभग बिना मेहनत के बहुभाषी बनाते हैं।',
    'description_provider': 'प्रोवाइडर',
    'description_hook': 'अनुवाद हुक',
    'description_selector': 'भाषा चयनकर्ता',
  },
  'zh-CN': {
    'heading': '适用于小型 React 应用的轻量 i18n 库',
    'description': 'Polang 提供 {{provider}}、{{hook}} 和 {{selector}}，三个小组件，几乎不费力气即可为你的 React 应用做国际化。',
    'description_provider': 'Provider',
    'description_hook': '翻译 Hook',
    'description_selector': '语言选择器',
  },
  'ja-JP': {
    'heading': '小さな React アプリ向けのミニ i18n ライブラリ',
    'description': 'Polang は {{provider}}、{{hook}}、{{selector}} の 3 つで、ほとんど手間なく React アプリを多言語化できます。',
    'description_provider': 'プロバイダ',
    'description_hook': '翻訳フック',
    'description_selector': '言語セレクター',
  },
};

export default translations;
